controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Arreglo;
use app\models\Cliente;
use app\models\Materiales;
use app\models\Ordenadores;
use app\models\Proveedores;
use app\models\Trabajador;
use yii\data\ActiveDataProvider;
use app\models\FormRegister;
use app\models\Users;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\models\FormSearch;

class SiteController extends Controller
{

 private function randKey($str='', $long=0)
    {
        $key = null;
        $str = str_split($str);
        $start = 0;
        $limit = count($str)-1;
        for($x=0; $x<$long; $x++)
        {
            $key .= $str[rand($start, $limit)];
        }
        return $key;
    }
  
 public function actionConfirm()
 {
    $table = new Users;
    if (Yii::$app->request->get())
    {
   
        //Obtenemos el valor de los parámetros get
        $id = Html::encode($_GET["id"]);
        $authKey = $_GET["authKey"];
    
        if ((int) $id)
        {
            //Realizamos la consulta para obtener el registro
            $model = $table
            ->find()
            ->where("id=:id", [":id" => $id])
            ->andWhere("authKey=:authKey", [":authKey" => $authKey]);
 
            //Si el registro existe
            if ($model->count() == 1)
            {
                $activar = Users::findOne($id);
                $activar->activate = 1;
                if ($activar->update())
                {
                    echo "Enhorabuena registro llevado a cabo correctamente, redireccionando ...";
                    echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";
                }
                else
                {
                    echo "Ha ocurrido un error al realizar el registro, redireccionando ...";
                    echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";
                }
             }
            else //Si no existe redireccionamos a login
            {
                return $this->redirect(["site/login"]);
            }
        }
        else //Si id no es un número entero redireccionamos a login
        {
            return $this->redirect(["site/login"]);
        }
    }
 }
 
 public function actionRegister()
 {
  //Creamos la instancia con el model de validación
  $model = new FormRegister;
   
  //Mostrará un mensaje en la vista cuando el usuario se haya registrado
  $msg = null;
   
  //Validación mediante ajax
  if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax)
        {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
   
  //Validación cuando el formulario es enviado vía post
  //Esto sucede cuando la validación ajax se ha llevado a cabo correctamente
  //También previene por si el usuario tiene desactivado javascript y la
  //validación mediante ajax no puede ser llevada a cabo
  if ($model->load(Yii::$app->request->post()))
  {
   if($model->validate())
   {
    //Preparamos la consulta para guardar el usuario
    $table = new Users;
    $table->username = $model->username;
    $table->email = $model->email;
    //Encriptamos el password
    $table->password = crypt($model->password, Yii::$app->params["salt"]);
    //Creamos una cookie para autenticar al usuario cuando decida recordar la sesión, esta misma
    //clave será utilizada para activar el usuario
    $table->authKey = $this->randKey("abcdef0123456789", 200);
    //Creamos un token de acceso único para el usuario
    $table->accessToken = $this->randKey("abcdef0123456789", 200);
     
    //Si el registro es guardado correctamente
    if ($table->insert())
    {
     //Nueva consulta para obtener el id del usuario
     //Para confirmar al usuario se requiere su id y su authKey
     $user = $table->find()->where(["email" => $model->email])->one();
     $id = urlencode($user->id);
     $authKey = urlencode($user->authKey);
      
     $subject = "Confirmar registro";
     $body = "<h1>Haga click en el siguiente enlace para finalizar tu registro</h1>";
     $body .= "<a href='http://yii.local/index.php?r=site/confirm&id=".$id."&authKey=".$authKey."'>Confirmar</a>";
      
     //Enviamos el correo
     Yii::$app->mailer->compose()
     ->setTo($user->email)
     ->setFrom([Yii::$app->params["adminEmail"] => Yii::$app->params["title"]])
     ->setSubject($subject)
     ->setHtmlBody($body)
     ->send();
     
     $model->username = null;
     $model->email = null;
     $model->password = null;
     $model->password_repeat = null;
     
     $msg = "Enhorabuena, ahora sólo falta que confirmes tu registro en tu cuenta de correo";
    }
    else
    {
     $msg = "Ha ocurrido un error al llevar a cabo tu registro";
    }
     
   }
   else
   {
    $model->getErrors();
   }
  }
  return $this->render("register", ["model" => $model, "msg" => $msg]);
 }
 
     public function actionUser()
     {
        return $this->render("user");
    }
     
    //Funcion para admin
    public function actionAdmin()
    {
        return $this->render("admin");
    }
    
     public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
   
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
     
    public function actionLogin()
    {

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->render('admin', [
                'model' => $model,
            ]);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }    

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
   

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionConsulta10a(){
        $dataProvider = new ActiveDataProvider([
            'query' => Proveedores::find() ->select("nombre, id_empresa"),
            
            'pagination'=>[
                'pagesize'=>5,
            ]
        ]);
                return $this->render ("resultado",[
                    "resultados" =>$dataProvider,
                    "campos"=>['nombre','id_empresa'],
            //a continuacion nada necesario -->
                    "titulo"=>"Nuestros proveedores",
                    ]
                        );
                
    }
     public function actionConsulta2a(){
        $dataProvider = new ActiveDataProvider([
            'query' => Materiales::find()->select("tipo,cantidad,estado"),
            'pagination'=>[
                'pagesize'=>5,
            ]
        ]);
                return $this->render ("resultado",[
                    "resultados" =>$dataProvider,
                    "campos"=>['tipo','cantidad','estado'],
            //a continuacion nada necesario -->
                    "titulo"=>"Estado de materiales actuales",
                    
                ]
                        );
    }
     public function actionConsulta3a(){
        $dataProvider = new ActiveDataProvider([
            'query' => Ordenadores::find()->select("n_averia,error,ncliente"),
            'pagination'=>[
                'pagesize'=>5,
            ]
        ]);
                return $this->render ("resultado",[
                    "resultados" =>$dataProvider,
                    "campos"=>['n_averia','error','ncliente'],
            //a continuacion nada necesario -->
                    "titulo"=>"Estado actual de las averias",
                    
                ]
                        );
    }
    
     public function actionConsulta4a(){
        $dataProvider = new ActiveDataProvider([
            'query' => Trabajador::find() ->select("cod_empleado,nombre, puesto"),
            
            'pagination'=>[
                'pagesize'=>5,
            ]
        ]);
                return $this->render ("resultado",[
                    "resultados" =>$dataProvider,
                    "campos"=>['cod_empleado','nombre','puesto'],
            //a continuacion nada necesario -->

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<h1> Localizacion </h1>

 
<div class="col-md-7">
<hr>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3175.4175777895334!2d-6.945200485119678!3d37.26152387985612!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd11d021b8461639%3A0x6b1c367c9bcfdcfc!2sAv.%20de%20Andaluc%C3%ADa%2C%2021004%20Huelva!5e0!3m2!1ses!2ses!4v1591555474415!5m2!1ses!2ses" width="500" height="350" frameborder="1" style="border:1;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</hr>
</div>  

views/site/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<!DOCTYPE html>

 

    
    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <?= Html::img('@web/images/horario.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
          <div class="container">
            <div class="carousel-caption">
              <!--
              <h1>Example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-large btn-primary" href="#">Sign up today</a></p>
              -->
            </div>
          </div>
        </div>
          
          <br/>
    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

     <!-- Three columns of text below the carousel -->
       <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
             <h2>Proveedores</h2>
              <br> 
           <?= Html::img('@web/images/proveedores.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
          <br>
          <br>
          
          
          
          
          
          <?= Html::a('Revisar', ['site/consulta10a'], ['class' => 'btn btn-primary'])?>
        
        </div><!-- /.col-lg-4 -->
        
        
        <div class="col-lg-4">
            <h2>Stock</h2>
            <br>
         <?= Html::img('@web/images/stock.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
          <br>
          <br>
          <?= Html::a('Revisar', ['site/consulta2a'], ['class' => 'btn btn-primary'])?>
         
        </div><!-- /.col-lg-4 -->
        
        <div class="col-lg-4">
             <h2>Averias</h2>
              <br>
         <?= Html::img('@web/images/averias.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
           <br>
          <br>
                 
                 
          <?= Html::a('Revisar', ['site/consulta3a'], ['class' => 'btn btn-primary'])?>
           </div>
   
        <div class="col-lg-4">
            <h2>Empleados</h2>
            <br>
            <?= Html::img('@web/images/Empleados.png', ['alt'=>'Empleados'], ['class'=>'img-circle']);?> 
            <br>
            <br>
          <?= Html::a('Revisar', ['site/consulta4a'], ['class' => 'btn btn-primary'])?>
          
        </div><!-- /.col-lg-4 -->

      
       <div class="col-lg-4">
           <h2>Clientes</h2>
           <br>
        <?= Html::img('@web/images/Cliente.png', ['alt'=>'Clientes'], ['class'=>'img-circle']);?> 
           <br>
           <br>
          <?= Html::a('Revisar', ['site/consulta5a'], ['class' => 'btn btn-primary'])?>
          
        </div><!-- /.col-lg-4 -->
        
         <div class="col-lg-4">
             <h2>Pedidos</h2>
             <br>
         <?= Html::img('@web/images/compras.png', ['alt'=>'Arreglos'], ['class'=>'img-circle']);?> 
          <br>
           <br>
          <?= Html::a('Revisar', ['site/consulta6a'], ['class' => 'btn btn-primary'])?>
          
        </div><!-- /.col-lg-4 -->
   
  </div><!-- /.row -->
       </div>


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">BackEnd de nuestro Taller</h2>
          <p class="lead">Pagina destinada a el control del almacenamiento y actuacion de Talleres Icarus </p>
        </div> 
        <div class="col-md-5">
           <?= Html::img('@web/images/Logo.png', ['alt'=>'Logo'], ['class'=>'img-circle']);?>
        </div>
      </div>

    


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2020 Talleres, Inc. &middot; </p>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./js/jquery.js"></script>
    <script src="./js/bootstrap.min.js"></script>
    <script src="./js/holder.js"></script>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'Control de Taller';
?>


    <div id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <?= Html::img('@web/images/horario.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
          <div class="container">
            <div class="carousel-caption">
              <!--
              <h1>Example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-large btn-primary" href="#">Sign up today</a></p>
              -->
            </div>
          </div>
        </div>
        <div class="item">
          <?= Html::img('@web/images/horario.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
          <div class="container">
            <div class="carousel-caption">
              <!--
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-large btn-primary" href="#">Learn more</a></p>
              -->
            </div>
          </div>
        </div>
        <div class="item">
          <?= Html::img('@web/images/horario.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
          <div class="container">
            <div class="carousel-caption">
              <!--
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-large btn-primary" href="#">Browse gallery</a></p>
              -->
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
             <h2>Proveedores</h2>
              <br> 
           <?= Html::img('@web/images/proveedores.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
          <br>
          <br>
          
          
          
          
          
          <?= Html::a('Revisar', ['site/consulta10a'], ['class' => 'btn btn-primary'])?>
        
        </div><!-- /.col-lg-4 -->
        
        
        <div class="col-lg-4">
            <h2>Stock</h2>
            <br>
         <?= Html::img('@web/images/stock.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
          <br>
          <br>
          <?= Html::a('Revisar', ['site/consulta2a'], ['class' => 'btn btn-primary'])?>
         
        </div><!-- /.col-lg-4 -->
        
        <div class="col-lg-4">
             <h2>Averias</h2>
              <br>
         <?= Html::img('@web/images/averias.jpg', ['alt'=>'proveedores'], ['class'=>'img-circle']);?>
           <br>
          <br>
                 
                 
          <?= Html::a('Revisar', ['site/consulta3a'], ['class' => 'btn btn-primary'])?>
           </div><!-- /.col-lg-4 -->

      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">BackEnd de nuestro Taller</h2>
          <p class="lead">Pagina destinada a el control del almacenamiento y actuacion de Talleres Icarus</p>
        </div> 
      <div class="col-md-5">
           <?= Html::img('@web/images/Logo.png', ['alt'=>'Logo'], ['class'=>'img-circle']);?>
        </div>

    


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2020 Talleres, Inc. &middot; <a href="#">Privacy</a> 
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./js/jquery.js"></script>
    <script src="./js/bootstrap.min.js"></script>
    <script src="./js/holder.js"></script>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

   
</div>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;



?>

<h3><?= $msg ?></h3>

<h1>Register</h1>
<?php $form = ActiveForm::begin([
    'method' => 'post',
 'id' => 'formulario',
 'enableClientValidation' => false,
 'enableAjaxValidation' => true,
]);
?>
<div class="form-group">
 <?= $form->field($model, "username")->input("text") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "email")->input("email") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "password")->input("password") ?>   
</div>

<div class="form-group">
 <?= $form->field($model, "password_repeat")->input("password") ?>   
</div>

<?= Html::submitButton("Register", ["class" => "btn btn-primary"]) ?>

<?php $form->end() ?>

views/site/resultado.php
<?php

   use yii\grid\GridView;
    use yii\widgets\Pjax;
    ?>
    

<div class="jumbotron">
    <h2>
        <?=$titulo?>
    </h2>
    
</div>

 <?= GridView::widget([
    'dataProvider' => $resultados,
    'columns' =>$campos,
    
]);?>